#!/bin/bash
# By graysky <graysky AT archlinux DOT us>
# Inspired by some code originally  written by Colin Verot

# nothing to do if there is no conf file
if [[ ! -f /etc/asd.conf ]]; then
	echo "Cannnot find /etc/asd.conf so bailing.  Reinstall package to use profile-sync-daemon."
	exit 0
else
	. /etc/asd.conf
fi

# nothing to do if these are empty
if [[ -z "${WHATTOSYNC[0]}" ]]; then
	echo "Must define at least one directory in the WHATTOSYNC array in /etc/asd.conf"
	exit 0
fi

[[ -z "$VOLATILE" ]] && VOLATILE="/dev/shm"
[[ -z "$PREFIX_PERMISSIONS" ]] && PREFIX_PERMISSIONS=700

DAEMON_FILE="/run/asd"

check() {
	local DIR USER BACKUP LINK
	for DIR in "${WHATTOSYNC[@]}"; do
		BACKUP="$DIR-backup_asd"  # this is the hdd bound backup in case of power failure
		if [[ -d "$BACKUP" ]]; then
			USER=$(/usr/bin/stat -c %U "$BACKUP")
		else
			USER=$(/usr/bin/stat -c %U "$DIR")
		fi
		LINK="$VOLATILE/asd-$USER$DIR"

		# if the machine was ungracefully shutdown then the backup will be on the filesystem
		# and the link to tmpfs will be on the filesystem but the contents will be empty
		# we need to simply remove the link and rotate the backup into place

		if [[ -e "$LINK/.flagged" ]]; then
			# all is well so continue
			/bin/true
		else
			[[ -h "$DIR" ]] && unlink "$DIR"
			[[ -d "$BACKUP" ]] && mv "$BACKUP" "$DIR"
		fi
	done
}

sync() {
	touch "$DAEMON_FILE"

	# sync to tmpfs and back again
	local DIR USER BACKUP LINK
	for DIR in "${WHATTOSYNC[@]}"; do
		BACKUP="$DIR-backup_asd"  # this is the hdd bound backup in case of power failure
		if [[ -d "$BACKUP" ]]; then
			USER=$(/usr/bin/stat -c %U "$BACKUP")
		else
			USER=$(/usr/bin/stat -c %U "$DIR")
		fi
		LINK="$VOLATILE/asd-$USER$DIR"

		# make tmpfs container
		if [[ -d "$DIR" ]]; then
			[[ -r "$LINK" ]] || su -c "install -dm$PREFIX_PERMISSIONS '$LINK'" $USER

			# backup target and link to tmpfs container
			if [[ "$(readlink "$DIR")" != "$LINK" ]]; then
				mv "$DIR" "$BACKUP"
				ln -s "$LINK" "$DIR"
			fi

			# sync the tmpfs targets to the disc
			if [[ -e $LINK/.flagged ]]; then
				su -c "rsync -a --delete --exclude .flagged '$LINK/' '$BACKUP/'" $USER
			else
				su -c "rsync -a '$BACKUP/' '$LINK/'" $USER
				su -c "touch '$LINK/.flagged'" $USER
			fi
		fi
	done
}

unsync() {
	local DIR USER BACKUP LINK
	for DIR in "${WHATTOSYNC[@]}"; do
		BACKUP="$DIR-backup_asd"  # this is the hdd bound backup in case of power failure
		USER=$(/usr/bin/stat -c %U "$BACKUP")
		LINK="$VOLATILE/asd-$USER$DIR"

		# remove link and move data from tmpfs to disk
		if [[ -h "$DIR" ]]; then
			unlink "$DIR"
			#	this assumes that the backup is always updated so be sure to invoke a sync
			# before an unsync
			#
			# restore original dirtree
			[[ -d "$BACKUP" ]] && mv "$BACKUP" "$DIR"
			[[ -d "$LINK" ]] && rm -rf "$VOLATILE/asd-$USER"
		fi
	done
	rm -f -- "$DAEMON_FILE"
}

case "$1" in
	sync)
		[[ ! -f $DAEMON_FILE ]] && check
		sync
		;;
	unsync)
		# make sure the daemon ran to setup the links
		[[ -f $DAEMON_FILE ]] && sync && unsync
		;;
	*) 
		echo -en "\E[31musage: $0 {sync}"
		tput sgr0 # reset colors to normal
		echo
		echo "sync) force a manual sync"
		;;
esac
exit 0
